conciliacion/urls.py
from django.urls import include, path
from django.contrib import admin

from conciliacion import views
from .views import BasicListView
from .models import Balance

from rest_framework import routers
from conciliacion import views

router = routers.DefaultRouter()
router.register(r'cuentasContables', views.BalanceViewSet)

urlpatterns = [
    path("", views.login, name="login"),
    path("menu", views.menu, name="menu"),
    path("logout", views.logout, name="logout"),
    path("clientes", views.customers, name="clientes"),
    path("invoice", views.invoice, name="invoice"),
    path("receipts", views.receipts, name="receipts"),
    path("balance", views.impConciliacion, name="balance"),
    path("emitidas", views.repEmitidas, name="emitidas"),
    path("recibidas", views.repRecibidas, name="recibidas"),
    path("conciliacion", views.conciliacion, name="conciliacion"),
    # path('conciliacion/<str:cuenta>/<str:campo_1>/<str:campo_2>/<str:tabla>/<str:title_1>/<str:title_2>', views.conciliacion, name='conciliacion'),
    path("export", views.export_data, name="export"),
    path("impbalanza", views.impbalanza, name="impbalanza"),
    path("delete/<str:balanza_id>", views.delete_balanza),
    path("deletefactem/<int:factemitidas_id>", views.delete_factemitidas),
    path("deletefactrec/<int:factrecibidas_id>", views.delete_factrecibidas),
    path("pagoprov", views.pagoprov, name="pagoprov"),
    path("country-list/", BasicListView.as_view(model=Balance), name="country_list"),
    path("invoiceDetail/<str:UUID>",views.invoiceDetail,name="invoiceDetail"),
    #path("detailFact/<str:UUIDInt>/<str:RFC>/<str:Periodo>/<str:Mes>/<str:Moneda>", views.detailFact, name="detailFact"),
    path("detailFact/<str:UUIDInt>", views.detailFact, name="detailFact"),
    path("parcialidades", views.parcialidades, name="parcialidades"),
    path("calcNomina", views.calcNomina, name="calcNomina"),
    path("calcIMSS", views.calcIMSS, name="calcIMSS"),
    path("reportePPD", views.reportePPD, name="reportePPD"),
    path("reporteRecibidas", views.reporteRecibidas, name="reporteRecibidas"),
    path("factParciales", views.factParciales, name="factParciales"),
    path("factParcialesRecibidas", views.reporteRecibidas, name="factParcialesRecibidas"),
    path("testPDF", views.testPDF, name="testPDF"),
    path("listas", views.listasNegras, name="listas"),

    path('', include(router.urls)),
]

admin.site.site_header = 'Olvera Contadores'

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('conciliacion.urls')),
]

conciliacion/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
import uuid

# Create your models here.

################## Clases anteriores

class InvoiceEmitidas(models.Model):
    Verificado_ó_Asoc = models.CharField(max_length=150, blank=False)
    Estado_SAT = models.CharField(max_length=150, blank=False)
    Version = models.CharField(max_length=150, blank=False)
    Tipo = models.CharField(max_length=150, blank=False)
    Fecha_Emision = models.CharField(max_length=150, blank=False)
    Fecha_Timbrado = models.CharField(max_length=150, blank=False)
    EstadoPago = models.CharField(max_length=150, blank=False)
    FechaPago = models.CharField(max_length=150, blank=False)
    Serie = models.CharField(max_length=150, blank=False)
    Folio = models.CharField(max_length=150, blank=False)
    UUID = models.CharField(max_length=150, blank=False)
    UUID_Relacion = models.CharField(max_length=150, blank=False)
    RFC_Emisor = models.CharField(max_length=150, blank=False)
    Nombre_Emisor = models.CharField(max_length=150, blank=False)
    LugarDeExpedicion = models.CharField(max_length=150, blank=False)
    RFC_Receptor = models.CharField(max_length=150, blank=False)
    Nombre_Receptor = models.CharField(max_length=150, blank=False)
    ResidenciaFiscal = models.CharField(max_length=150, blank=False)
    NumRegIdTrib = models.CharField(max_length=150, blank=False)
    UsoCFDI = models.CharField(max_length=150, blank=False)
    SubTotal = models.CharField(max_length=150, blank=False)
    Descuento = models.CharField(max_length=150, blank=False)
    Total_IEPS = models.CharField(max_length=150, blank=False)
    IVA_16 = models.CharField(max_length=150, blank=False)
    Retenido_IVA = models.CharField(max_length=150, blank=False)
    Retenido_ISR = models.CharField(max_length=150, blank=False)
    ISH = models.CharField(max_length=150, blank=False)
    Total = models.CharField(max_length=150, blank=False)
    TotalOriginal = models.CharField(max_length=150, blank=False)
    Total_Trasladados = models.CharField(max_length=150, blank=False)
    Total_Retenidos = models.CharField(max_length=150, blank=False)
    Total_LocalTrasladado = models.CharField(max_length=150, blank=False)
    Total_LocalRetenido = models.CharField(max_length=150, blank=False)
    Complemento = models.CharField(max_length=150, blank=False)
    Moneda = models.CharField(max_length=150, blank=False)
    Tipo_De_Cambio = models.CharField(max_length=150, blank=False)
    Forma_De_Pago = models.CharField(max_length=150, blank=False)
    Metodo_de_Pago = models.CharField(max_length=150, blank=False)
    NumCtaPago = models.CharField(max_length=150, blank=False)
    Condicion_de_Pago = models.CharField(max_length=150, blank=False)
    Conceptos = models.CharField(max_length=150, blank=False)
    Combustible = models.CharField(max_length=150, blank=False)
    IEPS_3 = models.CharField(max_length=150, blank=False)
    IEPS_6 = models.CharField(max_length=150, blank=False)
    IEPS_7 = models.CharField(max_length=150, blank=False)
    IEPS_8 = models.CharField(max_length=150, blank=False)
    IEPS_9 = models.CharField(max_length=150, blank=False)
    IEPS_265 = models.CharField(max_length=150, blank=False)
    IEPS_30 = models.CharField(max_length=150, blank=False)
    IEPS_53 = models.CharField(max_length=150, blank=False)
    IEPS_160 = models.CharField(max_length=150, blank=False)
    Archivo_XML = models.CharField(max_length=150, blank=False)
    Direccion_Emisor = models.CharField(max_length=150, blank=False)
    Localidad_Emisor = models.CharField(max_length=150, blank=False)
    Direccion_Receptor = models.CharField(max_length=150, blank=False)
    Localidad_Receptor = models.CharField(max_length=150, blank=False)
    IVA_8 = models.CharField(max_length=150, blank=False)
    IEPS_304 = models.CharField(max_length=150, blank=False)
    IVA_Ret_6 = models.CharField(max_length=150, blank=False)
    AÑO_Facturado = models.CharField(max_length=150, blank=False)
    Mes_Facturado = models.CharField(max_length=150, blank=False)
    Proyecto = models.CharField(max_length=150, blank=False)
    Evento = models.CharField(max_length=150, blank=False)
    SOCIO_EVENTO = models.CharField(max_length=150, blank=False)
    NOMBRE_EVENTO = models.CharField(max_length=150, blank=False)
    Forma_Cobro = models.CharField(max_length=150, blank=False)
    ASOCIADOS_NO_ASOCIADOS = models.CharField(max_length=150, blank=False)
    Año_cobro = models.CharField(max_length=150, blank=False)
    Mes_Cobro = models.CharField(max_length=150, blank=False)
    NOTAS = models.CharField(max_length=150, blank=False)
    FOLIO_2 = models.CharField(max_length=150, blank=False)
    COMPLEMENTO_DE_PAGO = models.CharField(max_length=150, blank=False)
    timestamp = models.DateTimeField(
        auto_now_add=True, editable=False, null=False, blank=False, verbose_name="Fecha"
    )
    last_modified = models.DateTimeField(
        auto_now=True,
        editable=False,
        null=False,
        blank=False,
        verbose_name="Ultima Actualización",
    )

class InvoiceRecibidas(models.Model):
    Verificado_ó_Asoc = models.CharField(max_length=150, blank=False)
    Estado_SAT = models.CharField(max_length=150, blank=False)
    Version = models.CharField(max_length=150, blank=False)
    Tipo = models.CharField(max_length=150, blank=False)
    Fecha_Emision = models.CharField(max_length=150, blank=False)
    Fecha_Timbrado = models.CharField(max_length=150, blank=False)
    EstadoPago = models.CharField(max_length=150, blank=False)
    FechaPago = models.CharField(max_length=150, blank=False)
    Serie = models.CharField(max_length=150, blank=False)
    Folio = models.CharField(max_length=150, blank=False)
    UUID = models.CharField(max_length=150, blank=False)
    UUID_Relacion = models.CharField(max_length=150, blank=False)
    RFC_Emisor = models.CharField(max_length=150, blank=False)
    Nombre_Emisor = models.CharField(max_length=150, blank=False)
    LugarDeExpedicion = models.CharField(max_length=150, blank=False)
    RFC_Receptor = models.CharField(max_length=150, blank=False)
    Nombre_Receptor = models.CharField(max_length=150, blank=False)
    ResidenciaFiscal = models.CharField(max_length=150, blank=False)
    NumRegIdTrib = models.CharField(max_length=150, blank=False)
    UsoCFDI = models.CharField(max_length=150, blank=False)
    SubTotal = models.CharField(max_length=150, blank=False)
    Descuento = models.CharField(max_length=150, blank=False)
    Total_IEPS = models.CharField(max_length=150, blank=False)
    IVA_16 = models.CharField(max_length=150, blank=False)
    Retenido_IVA = models.CharField(max_length=150, blank=False)
    Retenido_ISR = models.CharField(max_length=150, blank=False)
    ISH = models.CharField(max_length=150, blank=False)
    Total = models.CharField(max_length=150, blank=False)
    TotalOriginal = models.CharField(max_length=150, blank=False)
    TotalTrasladados = models.CharField(max_length=150, blank=False)
    Total_Retenidos = models.CharField(max_length=150, blank=False)
    Total_LocalTrasladado = models.CharField(max_length=150, blank=False)
    Total_LocalRetenido = models.CharField(max_length=150, blank=False)
    Complemento = models.CharField(max_length=150, blank=False)
    Moneda = models.CharField(max_length=150, blank=False)
    Tipo_De_Cambio = models.CharField(max_length=150, blank=False)
    FormaDePago = models.CharField(max_length=150, blank=False)
    Metodo_de_Pago = models.CharField(max_length=150, blank=False)
    NumCtaPago = models.CharField(max_length=150, blank=False)
    Condicion_de_Pago = models.CharField(max_length=150, blank=False)
    Conceptos = models.CharField(max_length=150, blank=False)
    Combustible = models.CharField(max_length=150, blank=False)
    IEPS_3 = models.CharField(max_length=150, blank=False)
    IEPS_6 = models.CharField(max_length=150, blank=False)
    IEPS_7 = models.CharField(max_length=150, blank=False)
    IEPS_8 = models.CharField(max_length=150, blank=False)
    IEPS_9 = models.CharField(max_length=150, blank=False)
    IEPS_265 = models.CharField(max_length=150, blank=False)
    IEPS_30 = models.CharField(max_length=150, blank=False)
    IEPS_53 = models.CharField(max_length=150, blank=False)
    IEPS_160 = models.CharField(max_length=150, blank=False)
    Archivo_XML = models.CharField(max_length=150, blank=False)
    Direccion_Emisor = models.CharField(max_length=150, blank=False)
    Localidad_Emisor = models.CharField(max_length=150, blank=False)
    Direccion_Receptor = models.CharField(max_length=150, blank=False)
    Localidad_Receptor = models.CharField(max_length=150, blank=False)
    IVA_8 = models.CharField(max_length=150, blank=False)
    IEPS_304 = models.CharField(max_length=150, blank=False)
    IVA_Ret_6 = models.CharField(max_length=150, blank=False)
    AÑO = models.CharField(max_length=150, blank=False)
    MES_FACTURADO = models.CharField(max_length=150, blank=False)
    PROYECTO = models.CharField(max_length=150, blank=False)
    CONTABILIDAD = models.CharField(max_length=150, blank=False)
    ESTATUS_PAGO = models.CharField(max_length=150, blank=False)
    BANCO = models.CharField(max_length=150, blank=False)
    Mes_Pago_BANCO = models.CharField(max_length=150, blank=False)
    AÑO_PAGO_BANCO = models.CharField(max_length=150, blank=False)
    NOTAS = models.CharField(max_length=150, blank=False)
    TIPO_IVA = models.CharField(max_length=150, blank=False)
    DIOT_COEFICIENTE = models.CharField(max_length=150, blank=False)
    DIOT_BASE_16 = models.CharField(max_length=150, blank=False)
    DIOT_IVA = models.CharField(max_length=150, blank=False)
    COMPLEMENTO_DE_PAGO = models.CharField(max_length=150, blank=False)
    timestamp = models.DateTimeField(
        auto_now_add=True, editable=False, null=False, blank=False, verbose_name="Fecha"
    )
    last_modified = models.DateTimeField(

conciliacion/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import InvoiceEmitidas, DatosFactura, InProyecto, FormaPago, Balance, InContabilidad
from django.forms import ModelChoiceField
import datetime
from .services import cuentasContables

class RFC(forms.ModelForm):
    class Meta:
        model = InvoiceEmitidas
        fields = ["Nombre_Emisor", "RFC_Emisor"]
        
        
    RFC_Emisor = forms.ModelChoiceField(label="RFC", queryset=InvoiceEmitidas.objects.all().values_list('RFC_Emisor').distinct())
    #forms.ModelChoiceField(label="RFC", queryset=InvoiceEmitidas.objects.values('RFC_Emisor').distinct())
    
    def clean_rfc(self):
        RFC_Emisor = self.cleaned_data.get("RFC_Emisor")
        RFC_Emisor.replace("'", "")
        return RFC_Emisor
    
class UserModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.get_full_name()

class addDatos(forms.ModelForm):
    class Meta:
        model = DatosFactura
        fields = ["ProyectoCont", "Contabilidad", "FechaPago", "FormaPago", "Notas", "CuentaContable", "idUsuario", "UUIDInt"]
        
    #InProyecto = forms.ModelChoiceField(label="Ingresos proyectos", queryset=InProyecto.objects.all().values_list('InProyecto').distinct())
    ProyectoCont = forms.ModelChoiceField(label="Proyectos contabilidad", queryset=InProyecto.objects.all().order_by('InProyecto'))
    Contabilidad = forms.ModelChoiceField(label="Ingresos Contabilidad", queryset=InContabilidad.objects.all())
    #GaProyecto = forms.ModelChoiceField(label="Gastos Proyecto", queryset=GaProyecto.objects.all())
    #GaContabilidad = forms.ModelChoiceField(label="Gastos Contabilidad", queryset=GaContabilidad.objects.all())
    #idUsuario = forms.ModelChoiceField(label="Usuario", queryset=User.objects.all())
    UUIDInt = forms.CharField(widget = forms.HiddenInput())
    #FechaPago = forms.CharField(label='Fecha de pago')
    FechaPago = forms.DateTimeField(initial=datetime.date.today().strftime("%Y-%m-%d"), required=False, label="Fecha de pago")
    FormaPago = forms.ModelChoiceField(label="Forma de pago", queryset=FormaPago.objects.all().order_by('FormaPago'))
    Notas = forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20}), required=False)
    #CuentaContable = forms.ModelChoiceField(label="Cuenta contable", queryset=Balance.objects.values_list('Cuenta', flat=True).order_by('Cuenta').distinct())
    #CC = forms.ModelChoiceField(label="Cuenta contable", queryset=Balance.objects.all().distinct())
    #CHOICES = (('Option 1', 'Option 1'),('Option 2', 'Option 2'),)
    CuentaContable = forms.CharField(label="Cuenta contable")
    #idUsuario = forms.ModelChoiceField(label="Usuario", queryset=User.objects.all())
    idUsuario = UserModelChoiceField(label="Usuario", queryset=User.objects.filter(is_active=True))

    #def __init__(self, *args, **kwargs):
    #    super(addDatos, self).__init__(*args, **kwargs)
    #    self.fields['id'].queryset = Balance.objects.all()

mysite/templates/PPDRec.html
{% load static %}
{% load humanize %}

{% block content %}

<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Reporte PDF</title>
  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->
  <style>
    @page {
      size: "A4";
      margin: 1.0cm 1.5cm 3.5cm 1.5cm;
    }

    body {
      /*width: 100% !important;
      height: 100%;*/
      background: #fff;
      color: black;
      /*font-size: 100%;*/
      font-family: 'Roboto', sans-serif;
      line-height: 1.65;
      -webkit-font-smoothing: antialiased;
      -webkit-text-size-adjust: none;
    }

    html {
      /* default font-size is 16px - this is set in the default browser stylesheet */
      font-size: 10px;
      font-weight: 400;
      line-height: 1.5;
    }    
  </style>
</head>

<body>
  <main class="container">
    <h2>Olvera Contadores</h2>
    <h4>{{ Titulo }}</h4>
    <table class="table" id="tblInicial" style="font-size: smaller;">
      <thead class="thead-light">
        <tr>
          <th scope="col">Nombre Emisor</th>
          <th scope="col">RFC Emisor</th>
          <th scope="col">Nombre Receptor</th>
          <th scope="col">RFC Receptor</th>
          <th scope="col">Folio Interno</th>
          <th scope="col">Fecha</th>
          <th scope="col">Total</th>
          <th scope="col">No. Parcialidad</th>
          <th scope="col">Imp. Saldo Anterior</th>
          <th scope="col">Imp. Pagado</th>
          <th scope="col">Saldo Insoluto</th>
          <th scope="col">UUID Fact.</th>
          <th scope="col">UUID Complem.</th>
        </tr>
      </thead>
      <tbody>
        {% for dt in qry %}
        <tr>
          <!--<th scope="row">1</th>-->
          <td>{{ dt.Nombre }}</td>
          <td>{{ dt.Rfc }}</td>
          <td>{{ dt.Serie }} - {{ dt.Folio }}</td>
          <td>{{ dt.Fecha }}</td>
          <td>{{ dt.Total }}</td>
          <td>{{ dt.NumParcialidad }}</td>
          <td>{{ dt.ImpSaldoAnt }}</td>
          <td>{{ dt.ImpPagado }}</td>
          <td>{{ dt.ImpSaldoInsoluto }}</td>
          <td>{{ dt.UUID }} </td>
          <td>{{ dt.UUIDHijo }} </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </main>
</body>
</html>
{% endblock %}

mysite/templates/detailInvoice.html
<div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">{{ rel }}</h5>
            <button type="button" onclick="return cerrar_modal()" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
        <div class="modal-body">
            Factura {{ ID }}
    <div class="bg-light p-5 rounded">

        <div class="table-responsive">
            <table class="table table-sm">
                <thead>
                    <tr align="center">
                        <th scope="col">Folio</th>
                        <th scope="col">Moneda</th>
                        <th scope="col">Metodo de pago</th>
                        <th scope="col">No Parcialidad</th>
                        <th scope="col">Saldo anterior</th>
                        <th scope="col">Imp Pagado</th>
                        <th scope="col">Saldo Insoluto</th>                        
                    </tr>
                </thead>
                <tbody>
                    {% for dt in query %}
                    <tr align="center">
                        <th scope="row">{{ dt.Folio}} - {{ dt.Serie }}</th>
                        <td>{{ dt.MonedaDR }} </td>
                        <td>{{ dt.MetodoDePagoDR }}</td>
                        <td>{{ dt.NumParcialidad }}</td>
                        <td>{{ dt.ImpSaldoAnt }}</td>
                        <td>{{ dt.ImpPagado }}</td>
                        <td>{{ dt.ImpSaldoInsoluto }}</td>                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" onclick="return cerrar_modal()" class="btn btn-secondary"
        data-dismiss="modal">Cerrar</button>
</div>
</div>
</div>

mysite/templates/emitidas.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ titulo }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Exportar</button>
      </div>      
    </div>
  </div>
  <table class="table table-striped table-sm" id="example">
    <!-- <caption>List of users</caption> -->
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Año</th>
        <th scope="col">Mes</th>
        <th scope="col">Subtotal</th>
        <th scope="col">IVA 16%</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    <tbody>
    {% for dt in qry %}    
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ dt.Año }}</td>
        <td>{{ dt.Mes }}</td>
        <td>$ {{ dt.SubTotal|floatformat:"2"|intcomma }}</td>
        <td>$ {{ dt.IVA_16|floatformat:"2"|intcomma }}</td>
        <td>$ {{ dt.Total|floatformat:"2"|intcomma }}</td>
      </tr>
    {% endfor %}  
    </tbody>
  </table>
</main>

{% endblock %}

mysite/templates/factRecibidas.html
{% extends "base.html" %}
{% load humanize %}
{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ titulo }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Exportar</button>
      </div>      
    </div>
  </div>
  <table class="table table-striped table-sm" id="example">
    <!-- <caption>List of users</caption> -->
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Año</th>
        <th scope="col">Mes</th>
        <th scope="col">Subtotal</th>
        <th scope="col">IVA 16%</th>
        <th scope="col">Retenido IVA</th>
        <th scope="col">Retenido ISR</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    <tbody>
    {% for dt in qry %}    
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ dt.Año }}</td>
        <td>{{ dt.Mes }}</td>
        <td>$ {{ dt.SubTotal|floatformat:"2"|intcomma }}</td>
        <td>$ {{ dt.IVA_16|floatformat:"2"|intcomma }}</td>
        <td>$ {{ dt.Retenido_IVA|floatformat:"2"|intcomma }}</td>
        <td>$ {{ dt.Retenido_ISR|floatformat:"2"|intcomma }}</td>
        <td>$ {{ dt.Total|floatformat:"2"|intcomma }}</td>
      </tr>
    {% endfor %}  
    </tbody>
  </table>
</main>

{% endblock %}

mysite/templates/pagoProv.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}

<style>
    div.dataTables_wrapper {
        width: 100%;
        margin: 0 auto;
    }
</style>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    
      <div
        class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ titulo }} </h1>
    </div>
    

    <div class="row">
      <form method="POST" action="">{% csrf_token %}
        <select name="RFC_Emisor" class="select form-control" required id="id_RFC_Emisor"> 
          <option value="" selected>---------</option> 
          <option value="AMI830615IA0">AMI830615IA0</option> 
          <option value="SUFF690719CI8">SUFF690719CI8</option> 
        </select>
        <input type ='submit' value='Obtener reporte'>
    </form>
    </div>

    <div class="table-responsive">
        <table class="display nowrap" style="width:100%" id="ISR">
          <thead>            
            <tr>
              <th>INGRESOS</th>
              <th>Enero</th>
              <th>Febrero</th>          
              <th>Marzo</th>
              <th>Abril</th>
              <th>Mayo</th>
              <th>Junio</th>
              <th>Julio</th>
              <th>Agosto</th>
              <th>Septiembre</th>
              <th>Octubre</th>
              <th>Noviembre</th>
              <th>Diciembre</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>            
            <tr>
              <td>Serv. Prof. 16%</td>
              {% for dt in qryISR %}
              <td>{{ dt.Sub16|floatformat:"0"|intcomma }}</td>
              {% endfor %}
              <td>aqui total</td>
            </tr>            
            <tr>
              <td>TRANSPORTE 16%</td>
              {% for dt in qryISR_TR %}
              <td>{{ dt.TR_16 }}</td>
              {% endfor %}
            </tr>
            <tr>
              <td>Ingresos Exentos IVA</td>
              {% for dt in qryISR_IN %}
              <td>{{ dt.SP_16 }}</td>
              {% endfor %}
            </tr>
            <tr>
              <td>Ingresos obtenidos del mes</td>
            </tr>
            <tr>
              <td>Ingresos obtenidos acumulados</td>
            </tr>
            <tr>
              sasa
            </tr>
            
          </tbody>
        </table>
      </div>


</main>

<script>
    $(document).ready(function() {
    $('#ISR').DataTable( {
        "scrollX": true
    } );
} );
</script>

{% endblock %}

mysite/templates/reportes.html
{% extends "base.html" %}

{% block content %}

hola mundo
        
{% endblock %}